### ISSUE TITLE
Can't install on Python 3.9 on a M1 Mac 

### ISSUE THREAD

**Issue by AllanLeanderRostockHansen** [DanilZherebtsov/verstack#38]
I am trying to install on a M1 Mac under Python 3.9.13 using the Poetry package manager.
Installing works when I use `pip install verstack`, but poetry is a very popular option nowadays, so ideally the package should be able to install.

I have a blank virtual environment:

```toml
[tool.poetry]
name = "trying-out-verstack"
version = "0.0.1"
description = "Trying out the Verstack library, a library for helping data scientists with common tasks."
authors = ["Some name <some.name@email.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9.12,<3.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

I add verstack using the command `poetry add verstack`.
